### PR TITLE
Link libthemis_jni.so dynamically

### PR DESCRIPTION
**Pull request by ilammy**
Do not embed Themis, Soter, and cryptographic backend (if present) into libthemis_jni shared object. Instead, link it dynamically against Themis like a proper library.

It has been a nice experiment to provide self-contained library for Java. However, we are going to distribute the library as a proper system package and for that we will need to have it properly linked against its dependencies. Themis Core will be installed by the package manager so all dependencies are going to be satisfied.

## Checklist

- [X] Change is covered by automated tests
- [X] ~~Benchmark results are attached (if applicable)~~
- [X] The [coding guidelines] are followed
- [X] Public API has proper documentation
- [X] Example projects and code samples are updated if needed (in case of API changes)
- [X] ~~Changelog is updated if needed~~ minor change, will be included into packaging PR

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ilammy** [comment]
Also, export some private functions to make dynamic linkage possible. These are currently used by Themis JNI wrapper in order to operate secure_session_load() correctly. Strictly speaking, we should not be using these functions, but currently there is no way to allocate Secure Session instance suitable for secure_session_load() without using private header <themis/secure_session_t.h>. These functions are exported from the shared library, but we make no commitment to keeping them exported. They should be hidden back once secure_session_load() gets a better API. They would be marked as `THEMIS_PRIVATE_API` if we had that, but I don’t want to add more of that along with `SOTER_PRIVATE_API`.

**Comment by vixentael** [comment]
Changes LGTM, but need to test that building process works on different machines.

**Comment by Lagovas** [comment]
> Strictly speaking, we should not be using these functions, but currently there is no way to allocate Secure Session instance suitable for secure_session_load() without using private header <themis/secure_session_t.h>.

can you explain why we need to export `secure_session_<init|cleanup>` to use `secure_session_load`? I don't see where these functions used in load/save implementations: https://github.com/cossacklabs/themis/blob/b9062e512aa39a284fa4177a6dc4ca9a34f72c83/src/themis/secure_session_serialize.c

**Comment by ilammy** [comment]
> can you explain why we need to export `secure_session_<init|cleanup>` to use `secure_session_load`?

Sure.

They need to be exported because JNI library uses them here:

https://github.com/cossacklabs/themis/blob/0d97f5baad2f9293e7fa88532a74e3ac4b3abd79/jni/themis_session.c#L533-L538

and here:

https://github.com/cossacklabs/themis/blob/0d97f5baad2f9293e7fa88532a74e3ac4b3abd79/jni/themis_session.c#L575-L576

Note that JNI library does not use secure_session_create() and secure_session_destroy(), and it stores `secure_session_t` directly, not a _pointer_ to it like any other wrapper:

https://github.com/cossacklabs/themis/blob/0d97f5baad2f9293e7fa88532a74e3ac4b3abd79/jni/themis_session.c#L40-L45

All of this is because secure_session_load() accepts a pointer to an allocated instance of secure_session_t. We need to allocate enough memory for Secure Session object in order to use that function, and currently the only way to do this is to include a private header `<themis/secure_session_t.h>` which defines the layout of secure_session_t. Allocating secure_session_t in that way requires secure_session_init() and secure_session_cleanup() to be used instead of secure_session_create() and secure_session_destroy().

This is problematic because:

- we need to export functions that are considered private API
- we need to expose implementation details of secure_session_t
- we cannot change layout of secure_session_t in any way
- we cannot compile JNI library and Themis Core separately

This PR exports the functions as an easy way out and maintains status quo. A proper solution would involve hiding the implementation details and reengineering secure_session_load() so that it does not depend on those details to be known by the users.

**Comment by Lagovas** [comment]
discussed with @ilammy that will be better if we will add a new function which will create secure session from the dumped buffer and return a pointer. after that, we will update jni to use this new function without usage of private api secure session to be consistent with other public api and deprecate old function.

**Pull request merged**
