### PR TITLE
Hot fix: upgrade Android SDK version for React Native Themis

### PR DESCRIPTION
**Pull request by radetsky**
Hotfix for the issue https://github.com/cossacklabs/themis/issues/978

### CODE REVIEW

**Review by vixentael — APPROVED** [review]

**Comment by vixentael** [comment]
I think we should cherry pick this PR into `release/0.14` branch
https://github.com/cossacklabs/themis/pull/970/files

**Review by ilammy — APPROVED** [review]
React Native: 3-in-1 upgrade headaches!

**Comment by ilammy** [comment]
> I think we should cherry pick this PR into release/0.14 branch

That would be neat to get green builds, but it doesn't seem that any of those CI jobs are checking React Native, so I don't think this PR should be blocked by red CI.

For example, "Android emulator" job is unlikely to get fixed by rolling back the base system, and it's more of Android build system rot mitigated with upgrades on `master`, but without a backup plan for what to do with 0.14 maintenance.

**Comment by vixentael** [comment]
> I don't think this PR should be blocked by red CI

after seeing your comment in #980 I agree with you

**Comment by vixentael** [comment]
@radetsky please continue with release, once you have time, and with #980  once you have time again :)

**Pull request merged**
