### PR TITLE
Merge Stable

### PR DESCRIPTION
**Pull request by G1gg1L3s**
The continuation of #1013

### CODE REVIEW

**Comment by vixentael** [comment]
macos tests are failing 😢

**Comment by G1gg1L3s** [comment]
Among all the options, the worst fell out :c

The MSYS2 also fails, but due to the incorrect hashes which can only be updated after the merge.

**Comment by Lagovas** [comment]
and macos...
what are our actions after successful tests except msys2? we merge it into the master, update hashes for msys2, and what do next?

**Review by Lagovas — APPROVED** [review]
reviewed one more time. See new changes from last PRs and see old changes with fixes in boringssl and .msys2 updates...
Do you remember what we planned to bring in this PR except windows related changes?)

**Comment by Lagovas** [comment]
wow, green tests except msys. what we need for green msys?

**Comment by G1gg1L3s** [comment]
>  what we need for green msys?

Hmm, since we already have release assets for 0.15.0, we can specify hashes of those and it should work. I will try to create a separate PR for this to see what happens.

**Pull request merged**
