### PR TITLE
Makes NSError** argument __autoreleasing in scell_token, adds check a…

### PR DESCRIPTION
**Pull request by valeriyvan**
…gainst null dereference

### CODE REVIEW

**Comment by vixentael** [comment]
second part of #257 ?

**Comment by valeriyvan** [comment]
TL DR: same fix, but for other files.
Confused by same branch name?
All NSError ** should be __autoreleasing, otherwise it might lead to appearing of zombies.
And it's better to be ready for NSError* passed to be nil. Because it's common practice ignore detailed error info which NSError provides when method signals for error with nil return value. In that case NSError provides additional information which we don't always need.

**Comment by vixentael** [comment]
yes, you're right, we should expect nil as errors.

can you please update smessage and ssession classes too? just to be consistent everywhere

**Comment by vixentael** [comment]
Nah, our tests and examples are using themis pod from master branch, so CI can't indicate immediately that tests are failing.

I've found and fixed small issues in your PR
https://github.com/cossacklabs/themis/commit/ad36068dddd58017c79959aa7d07a460a0911d34
https://github.com/cossacklabs/themis/commit/b38fa55e3178b009cf139d8eb74bb0cf00beacfd

and merged it.

Thank you a lot!

**Pull request merged**
