### PR TITLE
Update Carthage examples to use Themis 0.13.2

### PR DESCRIPTION
**Pull request by vixentael**
After #705 0.13.2 release, let's keep iOS/macOS Carthage examples fresh!

Blocked by #707. 

## Checklist

- [x] Changelog is updated (in case of notable or breaking changes)

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by vixentael** [comment]
> Not really.
Yes, because I can't update ChangeLog yet :(

**Comment by ilammy** [comment]
> Blocked, because I can't update ChangeLog yet :(

Yes you can. Just have to deal with conflicts later ;)

**Comment by vixentael** [comment]
> Just have to deal with conflicts later ;)

**Comment by ilammy** [comment]
@vixentael,

just do it

The keyword here is

> **later**

**Pull request merged**
