### PR TITLE
Automate C code formatting [2/3]

### PR DESCRIPTION
**Pull request by ilammy**
Actually reformat the whole code base in accordance with the style.

Drop some commented out code that cause problems with formatting. clang-tidy and clang-format conflict in line-wrapping this part.

Supersedes #391, relates to #270

### CODE REVIEW

**Comment by Lagovas** [comment]
oh, I think we need to do something like 
```
find src \( -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.hpp" \) -type f -exec cat {} \; | \
  tr -d "[:space:]" | \
  strings -1 | sha256sum > /tmp/sum1
``` 
for code in branch and for original code and then `cmp` them to be sure that there was changed only formatting )) 
but it's not cover cases with changes one-lined if expressions that should be wrapped with braces *(

**Comment by ilammy** [comment]
Well, yeah. This change is somewhat problematic to review and audit. What if I told you that I'd inserted a backdoor somewhere in those 20k lines?

It is possible to verify that the suggested changes come from the previously added formatting changes. Do this:

```shell
# On your machine, current dir is Themis repo root dir:
$ git checkout 29d365553d8f4a5e74b1194eb5dc339d1210ada4
$ docker run -it --rm -v $PWD:/projects cossacklabs/build:ubuntu-bionic

# In Docker container:
$ export CLANG_FORMAT=clang-format-7
$ export CLANG_TIDY=clang-tidy-7
$ make fmt ENGINE=boringssl
$ make fmt ENGINE=openssl
$ ^D

# Back to your machine, compare the result with this PR:
$ git diff 672c057eb36ff06acacf4467373eec3f9a77fb3f
```

Aside from in the build system (not included into this PR), you should only see changes in "src/themis/secure_message_wrapper.h" as I removed some commented out code that caused trouble with formatting.

Actually, there are some missing changes in OpenSSL sources...

**Comment by ilammy** [comment]
Then we can separately inspect the changes introduced by clang-tidy (it can change semantics) and then the changes by clang-format (which should change only the formatting). However, inspecting the formatting changes would not be as straightforward as ignoring all whitespace because it may relocate braces between lines, break overlong lines, etc.

**Comment by Lagovas** [comment]
> What if I told you that I'd inserted a backdoor somewhere in those 20k lines?
huh, not only you can do this, `clang-[tidy|format]` can do it too.  by replacing some `>=` -> `<` or `!= 0` -> `== 0`. but it should be checked by tests as general (if they weren't updated with same tools too : )

**Comment by ilammy** [comment]
Well, yeah, that's assuming that we do trust the tools. They come from Debian repositories so I guess we can rule out blatant malicious behavior as someone on the Internet should have noticed that. We can also rule out blatantly erroneous semantic changes as that should be checked by the tests. But this does not account for some tricky vulnerability which may be inserted by replacing `<` with `<=`, or `==` with `=`.

**Comment by secumod** [comment]
Let's have descriptive commit header/message, like "apply make fmt"

**Comment by ilammy** [comment]
If that makes it any easier I have separated the changes into three individual commits: dropping a problematic code part, applying semantic fixes followed by the style fixes.

I have tried comparing without whitespace but clang-format introduces non-whitespace changes as well by adjusting the comments and stuff.

So I guess you'll just have to trust me and the tools. You can still verify that the changes are made by the tools using the process described above. Though I guess it would be better to use an exact Docker image hash. But I don't know for how long DockerHub stores these so there's no guarantee that this commit will be validatable in five years from now.

<details>
<summary>My docker inspect output</summary>
```console
$ docker inspect cossacklabs/build:ubuntu-bionic
[
    {
        "Id": "sha256:0371c8d5befb068a130fbecc261e4991052f858c19bbd89b0850ce9066e72a04",
        "RepoTags": [
            "cossacklabs/build:ubuntu-bionic"
        ],
        "RepoDigests": [
            "cossacklabs/build@sha256:8a83dc3916a9f6b56496982bde255cd530c09fe1ae2842b5a59b72f1bf0a5983"
        ],
        "Parent": "sha256:593a29058f2f22607d0bf194c1053bbe98ceb09a65a2d807a6a68e51ba41724b",
        "Comment": "",
        "Created": "2019-02-27T18:25:49.8226009Z",
        "Container": "702727bd86feb489348117614616297ac4371ca3e47bc87d37b41975471010ce",
        "ContainerConfig": {
            "Hostname": "702727bd86fe",
            "Domainname": "",
            "User": "user",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) WORKDIR /projects"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:593a29058f2f22607d0bf194c1053bbe98ceb09a65a2d807a6a68e51ba41724b",
            "Volumes": null,
            "WorkingDir": "/projects",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "18.09.1",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "user",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:593a29058f2f22607d0bf194c1053bbe98ceb09a65a2d807a6a68e51ba41724b",
            "Volumes": null,
            "WorkingDir": "/projects",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1412072723,
        "VirtualSize": 1412072723,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/480fe7b0508b1c57bb84b9d1c0dc6245f652ad5e9e4dca5e54145bd9fa1c1e7c/diff:/var/lib/docker/overlay2/efb1512a851d64105a27eb4b3a2078bfaddb71ba8fc79b65e058f14fd90b8bb8/diff:/var/lib/docker/overlay2/16a8820f0ba9c2a746dd9d4a2bac7f428df1a40c34c8a05a846c31ec8ed4aeb2/diff:/var/lib/docker/overlay2/c1ffba20384572d8e11f34dc0d4168cfbf1d98f949e00af37c5a936378efd535/diff:/var/lib/docker/overlay2/9d9cbe48e474638e90526cad2382d5be9aeb656106813d64f1fc6a5d74bd30f5/diff",
                "MergedDir": "/var/lib/docker/overlay2/af184e3ad564e24f1e4a5e8c13a32018ac82856a11a4f518aaf79245856f6abb/merged",
                "UpperDir": "/var/lib/docker/overlay2/af184e3ad564e24f1e4a5e8c13a32018ac82856a11a4f518aaf79245856f6abb/diff",
                "WorkDir": "/var/lib/docker/overlay2/af184e3ad564e24f1e4a5e8c13a32018ac82856a11a4f518aaf79245856f6abb/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:bebe7ce6215aee349bee5d67222abeb5c5a834bbeaa2f2f5d05363d9fd68db41",
                "sha256:283fb404ea9415ab48456fd8a82b153b1a719491cdf7b806d1853b047d00f27f",
                "sha256:663e8522d78b5b767f15b2e43885da5975068e3195bbbfa8fc3a082297a361c1",
                "sha256:4b7d93055d8781d27259ba5780938e6a78d8ef691c94ee9abc3616c1b009ec4a",
                "sha256:052e844a7399860ca6a5aceea82a061580e4234737ba290849ecf2d71ff4419e",
                "sha256:2f6f406a892efe4e01d55324b6700483ee56ff19970c0e50dab25e0e6b65b0e4"
            ]
        },
        "Metadata": {
            "LastTagTime": "2019-02-27T18:33:29.0245756Z"
        }
    }
]
```
</details>

**Pull request merged**
