### PR TITLE
Merge branch `master` into `wasm-typescript`

### PR DESCRIPTION
**Pull request by ilammy**
Sync changes on `master` with `wasm-typescript`, resolve merge conflicts. Most changes are unrelated to WasmThemis, but I want to pull dependency bumps that fix `npm audit` advisories. And speedy Ninja builds for BoringSSL.

TODO:
- [x] #846 is merged
- [x] This merge is redone, pulling in newer `master`

## Checklist

- [x] Change is covered by automated tests
- [x] The [coding guidelines] are followed

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

- [ ] This is a premade merge commit. **Do not** use GitHub PR UI for merging, just `git push` once approved.

### CODE REVIEW

**Comment by ilammy** [comment]
Oh, there a bunch of other tweaks to WasmThemis that I'd like to throw in (tests and examples). So I guess I'll put this PR to draft for the time being, then redo the merge.

**Comment by ilammy** [comment]
I've redone the merge. Now the branch includes newly added examples and tools for WasmThemis.

WasmThemis examples are expected to fail due to backwards-incompatible changes on `wasm-typescript` branch. These failures will be resolved after this merge. The merge discards changes to `tools` previously made by @maxammann and pulls in the `master` version of example code. This will show where the breakage is.

WasmThemis unit tests are expected to pass.

**Comment by ilammy** [comment]
Changed my mind once again and redone the merge. Now all tests are expect to pass, examples are expected to work.

Conflicts in `wasm/package-lock.json` have been resolved by merging changes from both branches.

There were also conflicts in `tools/js/wasm-themis` as 'wasm-typescript' branch has introduced some breaking changes in API. I've reconciled the changes between branches, favoring the "broken" API here. I've also updates other WasmThemis examples to use this API.

The plan is to get the CI running, helping with this, and then work on removing backwards-incompatible changes in later commits.

**Comment by vixentael** [comment]
> Now all tests are expect to pass

Well, tests are passing..

**Review by vixentael — APPROVED** [review]
I didn't review all the changes, because PRs is huge; you wrote "merge via console"; soooo if there's anything backdoory here, that's on you :D

**Comment by ilammy** [comment]
@vixentael, I don't have a good git fu to teach you on how to review merge commits between branches that *both* have loads of new commits on them.

“Trust me, I'm an engineer!”

The answer probably is don't let the situation deteriorate to this state 🤷

**Comment by vixentael** [comment]
> don't let the situation deteriorate to this state 🤷

in next life probably :)

**Comment by ilammy** [comment]
Well, at least you can check that I've merged the commit I intended to merge, not pushed something completely different.

**Pull request merged**
