### PR TITLE
themis: Bump PBKDF2 iterations to 314,110

### PR DESCRIPTION
**Pull request by ilammy**
It's been almost 3 years since this value was revised. Current OWASP recommendations are at least 310,000 iterations for SHA-256, so let's bump it up to be safe.

## Checklist

- [X] Change is covered by automated tests
- [X] Benchmark results are attached
- [X] The [coding guidelines] are followed
- [X] Public API has proper documentation
- [X] Changelog is updated

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by vixentael** [comment]
but it will break compatibility between themis versions

**Comment by Lagovas** [comment]
> but it will break compatibility between themis versions

no, it will not. iteration count [serialized](https://github.com/cossacklabs/themis/blob/master/src/themis/secure_cell_seal_passphrase.h#L256) in ciphertext structure on encryption and deserialized [on](https://github.com/cossacklabs/themis/blob/master/src/themis/secure_cell_seal_passphrase.h#L271) [decryption](https://github.com/cossacklabs/themis/blob/28eb6e63f8bd04fec99d44e578a24341dafdf062/src/themis/secure_cell_seal_passphrase.c#L321). This constant specifies how much iterations should be used on every new encryption operations. All previously encrypted contains iteration count and will be decrypted.

**Review by Lagovas — APPROVED** [review]
lgtm

**Comment by ilammy** [comment]
> > but it will break compatibility between themis versions
> 
> no, it will not. iteration count [serialized](https://github.com/cossacklabs/themis/blob/master/src/themis/secure_cell_seal_passphrase.h#L256) in ciphertext structure on encryption and deserialized [on](https://github.com/cossacklabs/themis/blob/master/src/themis/secure_cell_seal_passphrase.h#L271) [decryption](https://github.com/cossacklabs/themis/blob/28eb6e63f8bd04fec99d44e578a24341dafdf062/src/themis/secure_cell_seal_passphrase.c#L321)

That's the plan 👍

It is not a breaking change, should be transparent to the users. Except for the expected x2 time to encrypt/decrypt. I'd like to do some benchmarks first before merging this (with whatever the new value would be).

**Review by G1gg1L3s — APPROVED** [review]
Yeah, moar secuwity!

It would be cool to see some random looking number, for example, totally randomly generated from the first try without any enumeration:
```
echo -n "oh dear Random Oracle, we request the number of pbkdf2 rounds for Secure Cell that we should use in 2023" | sha256sum | head -c 6
487847
```

But nevermind :)

**Comment by vixentael** [comment]
> iteration count serialized in ciphertext structure 

oh, y'all are the best!! 🧡

**Comment by vixentael** [comment]
i am not a fan of 2x performance penalty, i suggest using `311002` iterations instead of 400000.

**Comment by ilammy** [comment]
As expected, most of the cost is in PBKDF and it's proportional to the iteration count.

<details>
<summary>Sample with n = 1</summary>

200,000 iterations:

```
Secure Cell encryption - Seal, passphrase/64                                                                            
                        time:   [166.01 ms 166.05 ms 166.11 ms]
                        thrpt:  [385.29   B/s 385.42   B/s 385.51   B/s]

Secure Cell decryption - Seal, passphrase/64                                                                            
                        time:   [166.10 ms 166.27 ms 166.57 ms]
                        thrpt:  [384.22   B/s 384.92   B/s 385.31   B/s]
```

400,000 iterations:

```
Secure Cell encryption - Seal, passphrase/64                                                                            
                        time:   [333.14 ms 333.61 ms 334.18 ms]
                        thrpt:  [191.52   B/s 191.84   B/s 192.11   B/s]

Secure Cell decryption - Seal, passphrase/64                                                                            
                        time:   [392.68 ms 393.21 ms 393.97 ms]
                        thrpt:  [162.45   B/s 162.76   B/s 162.98   B/s]
```

3,14159 iterations:

```
Secure Cell encryption - Seal, passphrase/64                                                                            
                        time:   [262.01 ms 262.51 ms 263.29 ms]
                        thrpt:  [243.08   B/s 243.80   B/s 244.27   B/s]

Secure Cell decryption - Seal, passphrase/64                                                                            
                        time:   [264.99 ms 266.50 ms 268.19 ms]
                        thrpt:  [238.64   B/s 240.15   B/s 241.52   B/s]
```

</details>

Somewhat in the previous measurement of 120 ms for the same machine. New value bumps that to 330 ms. (OpenSSL 3.0 might have been involved in slight degradation.)

@vixentael, how about 314159 iterations then? :wink:

**Comment by vixentael** [comment]
@ilammy `314158`

i'm suspicious about the odd (not even) round counts while I appreciate the 🥧.

**Pull request merged**
