### PR TITLE
Add dist target for distribution building

### PR DESCRIPTION
**Pull request by mnaza**

### CODE REVIEW

**Comment by Lagovas** [comment]
file with name `pp`? why so verbose?)

**Comment by mnaza** [comment]
Pre-processor

**Comment by Lagovas** [comment]
oh, I need extrasensory abilities to understand. what stop you to name `pre_processor.sh`? or just add extension .sh to show that it's script, not some binary file

**Comment by mnaza** [comment]
Agreed, for .sh, but it`s not fully preprocessor,  just pp :)

**Comment by Lagovas** [comment]
better to create separate folder where all files/scripts will be stored for builds and not litter root folder of repo, imho. today `pp`, tomorrow `cc`, week later -`b`.

**Comment by mnaza** [comment]
Move to separate .scripts folder

**Pull request merged**
