### PR TITLE
Secure usage of Emscripten heap

### PR DESCRIPTION
**Pull request by ilammy**
In order to call Themis Core functions we need to transfer key material and messages from JavaScript memory into Emscripten heap. Operations results are similarly transferred back to JavaScript memory. We do this by explicitly allocating a buffer on Emscripten heap and using Emscripten helpers for transfers.

One important point here is that all data is still retained for some time on Emscripten heap after `free()` is called. This includes sensitive data which theoretically may be accessed by an adversary. Generally it is recommended to wipe the memory that contains sensitive data after use. We can't control JavaScript memory, but we can at least ensure that Emscripten heap does not leave any unwanted traces.

Introduce some functions to help us with data transfer between JavaScript and Emscripten heaps. They are designed to be used together so any new code will naturally use them instead of reaching for C functions and Emscripten runtime directly.

----

- [x] Add common helper functions
- [x] Cover all cryptosystems
  - [x] Key generation (this PR)
  - [x] Secure Cell (#462)
  - [x] Secure Message (#490)
  - [x] Secure Comparator (#491)
  - [x] Secure Session (#492)

### CODE REVIEW

**Comment by ilammy** [comment]
Currently this covers only key generation. I'll add tests for other cryptosystems into this PR once they are merged.

**Comment by ilammy** [comment]
I've converted all allocations to use `heapAlloc` and `heapFree`. Now we should not be leaving any leaked data in Emscripten heap after Themis calls are complete. Obviously, the data will still be present there during the operation time, but it _has_ to be _somewhere_ in memory.

**Comment by ilammy** [comment]
> If I also understood correctly, we plan to use `utils.heapFree(...)` on errors?

We already do it in this PR. These calls are placed in **finally** blocks so they are executed in both the happy path and when an exception is thrown due to an error.

**Comment by vixentael** [comment]
Oh, i missed that we wrap everything in `try` blocks :)

**Comment by ilammy** [comment]
Your comment made me realize that we handle memory allocation errors poorly in the these utility functions. I've added a minor fix which allows using `headFree` on NULL values returned by failed `heapAlloc` invocation.

**Comment by vixentael** [comment]
that's actually makes sense! 💪

**Pull request merged**
