### PR TITLE
jsthemis: Downgrade mocha to ^7 for Centos7

### PR DESCRIPTION
**Pull request by G1gg1L3s**
This version and all its transitive dependencies support node v8 which is the only version we can run on centos 7. It seems like other OS work fine with it, at least on buildbot.

Another option is to fix our scripts on buildbot just for centos 7, so they patch the versions before testing. This may save us from future problems or dependency issues. However, downgrading dev dependency is not that scary, so maybe this approach is okay.

## Checklist

- [x] Change is covered by automated tests
- [x] ~Benchmark results are attached (if applicable)~
- [x] ~The [coding guidelines] are followed~
- [x] ~Public API has proper documentation~
- [x] ~Example projects and code samples are up-to-date (in case of API changes)~
- [x] ~Changelog is updated (in case of notable or breaking changes)~

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by G1gg1L3s** [comment]
Sure! We can adjust buildbot scripts: add a step with `sed` that will replace the version before testing. I don't know other ways of doing this, like adjusting package.json or something.

**Comment by G1gg1L3s** [comment]
Hmm, that is an option, thank you! However, it will [collide with the node-gyp](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#default-values) which we use to build the addon, so in this case we would have to explicitly call the node-gyp. So probably for these reasons npm doesn't recommend redefining `install` and `preinstall`. Also, this way is slightly harder to implement. In the end, this is just for tests, the addon itself works fine.

However, if you believe this this the right way, I can do it.

**Comment by G1gg1L3s** [comment]
@radetsky, could you take a quick look please. Does the last commit look like you described?

**Comment by G1gg1L3s** [comment]
Looks like buildbot tests are green, so thank you, @radetsky!

**Comment by vixentael** [comment]
Nice one!

@Lagovas WDYT?

**Review by Lagovas — APPROVED** [review]

**Review by vixentael — APPROVED** [review]

**Pull request merged**
