### PR TITLE
Update to OpenSSL 1.1.1g

### PR DESCRIPTION
**Pull request by ilammy**
It's enough for us to be slaves to ye olde OpenSSL 1.0.2. Embrace the blessing of OpenSSL 1.1.1 which does not require users to register mutex locking callbacks to be thread safe, and brings other improvements (in particular, non-broken bitcode).

Unfortunately, the providers that we used are not very eager on upgrading to OpenSSL 1.1.1, especially the CocoaPods one. So I took a shot at packaging it myself. This PR switches from https://github.com/krzyzanowskim/OpenSSL and https://github.com/levigroker/GRKOpenSSLFramework to https://github.com/cossacklabs/openssl-apple

### Carthage

The new OpenSSL is distributed as a binary-only framework. It will be downloaded from GitHub instead of building it from source. This is not much different from what the previous vendor did, but is more stable.

Carthage builds use the static flavor of the framework.  We have run into issues with dynamic frameworks of OpenSSL when using Carthage, but static frameworks seems to do very good job: the resulting binaries are smaller, apps start a bit faster, and users are freed from the hassle of dealing with OpenSSL linkage to their app.

Note that due to the way static linkage works, we will be exporting all OpenSSL symbols from ObjCThemis by default. In order to avoid conflicts, export only limited subset of symbols: Objective-C classes of ObjCThemis.

**For users:** It is now not required to link and embed `openssl.framework` into your application. Only `objcthemis.framework` needs to be included.

### CocoaPods

The new OpenSSL is distributed as a tricky pod (which also downloads binaries from GitHub), but for consumers like Themis it's just a pod.

Introduce a separate subspec for the build with newer OpenSSL, and make it the default choice. We keep the old specs around in case someone needs them to share GRKOpenSSL or BoringSSL with other dependencies, as it is not possible to use CLOpenSSL simultaneously with them due to OpenSSL symbol conflicts.

The new subspec has its oddities, but it's all (un)known magic that seems to be absolutely necessary to build Themis properly for iOS.

### Xcode update

Xcode 10.x is incompatible with bitcode provided by prebuilt OpenSSL frameworks. Therefore Xcode 11.0 is now the minimum required version for ObjCThemis and SwiftThemis.

### Experimental arm64e support

ObjCThemis installed with Carthage now enables [**arm64e** architecture](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication). You can test your apps with it as well. (For CocoaPods you will have to add the architecture to the workspace as outlined in Apple documentation above.)

The support is still experimental and is know to fail on some Xcode versions.

## Checklist

- [X] Change is covered by automated tests
- [X] The [coding guidelines] are followed
- [X] ~~Example projects and code samples are up-to-date~~ (should be updated after release)
- [X] Changelog is updated

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ilammy** [comment]
Well, _of course_ it fails! I don't have mental capacity to deal with it today, or I'm afraid I'll need a new Mac and some painting to hang on the wall which would have taken the hit.

**Comment by vixentael** [comment]
My testing results: themis-cocoapods works on iOS sims and devices; themis-carthage shows error during installation. Details in slack.

**Comment by ilammy** [comment]
Okay... One issue was in that I cherry-picked my old commit from the experimental branch which implemented exported symbols list, and that list did not include recently added `TSGenerateSymmetricKey()` which is a free function, not a class. This should resolve some Carthage build issues. But not everything.

**Comment by ilammy** [comment]
Another issues that are around:

- CocoaPods spec fails to lint because it pulls Themis from the `0.13.0` tag straight, which does not include fixes for OpenSSL 1.1.1 compatibility.

- Carthage on Bitrise fails with a weird error. Does this mean that Bitrise toolchain is too old?

```
Ld /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ (iOS)/IntermediateBuildFilesPath/ObjCThemis.build/Release-iphoneos/Themis\ (iOS).build/Objects-normal/armv7/objcthemis normal armv7 (in target: Themis (iOS))
    cd /Users/vagrant/git
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk -L/Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/BuildProductsPath/Release-iphoneos -F/Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/BuildProductsPath/Release-iphoneos -F/Users/vagrant/git/Carthage/Build/iOS -filelist /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/IntermediateBuildFilesPath/ObjCThemis.build/Release-iphoneos/Themis\ \(iOS\).build/Objects-normal/armv7/objcthemis.LinkFileList -exported_symbols_list /Users/vagrant/git/src/wrappers/themis/Obj-C/exported.symbols -install_name @rpath/objcthemis.framework/objcthemis -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/IntermediateBuildFilesPath/ObjCThemis.build/Release-iphoneos/Themis\ \(iOS\).build/Objects-normal/armv7/objcthemis_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/BuildProductsPath/Release-iphoneos -fobjc-arc -fobjc-link-runtime -framework openssl -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/IntermediateBuildFilesPath/ObjCThemis.build/Release-iphoneos/Themis\ \(iOS\).build/Objects-normal/armv7/objcthemis_dependency_info.dat -o /Users/vagrant/Library/Developer/Xcode/DerivedData/ObjCThemis-cokqrmmbnpmoxudrqhfueshqgzwf/Build/Intermediates.noindex/ArchiveIntermediates/ObjCThemis\ \(iOS\)/IntermediateBuildFilesPath/ObjCThemis.build/Release-iphoneos/Themis\ \(iOS\).build/Objects-normal/armv7/objcthemis
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1100.0.33.12.0_0' Reader: '1001.0.46.4_0')', using libLTO version 'LLVM version 10.0.1, (clang-1001.0.46.4)' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- @vixentael sees a different Carthage build failure with a lot of errors like

```
docs/examples/swift/iOS-Carthage/Carthage/Checkouts/themis/Carthage/Build/iOS/openssl.framework/Headers/bn.h:267:33: error: unknown type name 'BN_ULONG'
BN_ULONG BN_div_word(BIGNUM *a, BN_ULONG w);
```

which are preceded by 

```
docs/examples/swift/iOS-Carthage/Carthage/Checkouts/themis/Carthage/Build/iOS/openssl.framework/Headers/opensslconf.h:24:3: error: Unable to determine target or target not included in OpenSSL build
# error Unable to determine target or target not included in OpenSSL build
  ^
```

which suggests that the OpenSSL was not compiled for some architectures?..

**Comment by ilammy** [comment]
Previous Bitrise failure seems to have been caused by Bitrise using Xcode 10.3.x which cannot parse bitcode produce by my Xcode 11.2 used to build OpenSSL. Given than Xcode 11.6 is the current stable (= supported by Apple), I guess it's justified that we bump the requirements to Xcode 11.x. I have asked Bitrise to use Xcode 11.0.x on macOS 10.14 for builds from now on.

Also, merge conflicts prevented other tasks on Bitrise from finishing successfully. I have synced this PR with master, pushed. This _should_ (🤞) fix Bitrise. It also triggers GitHub Actions build. (No idea why changing `exported.symbols` did not.)

**Comment by ilammy** [comment]
Fixed up the “version hack” used for CocoaPods spec linting. It turned out that the previous version of the hack (added in #610) was not effective and did not actuall update the spec file. Now it is properly updated with the current commit. This should make the last broken build on GitHub Actions go green.

**Comment by ilammy** [comment]
The last issue – Carthage failure about missing architectures – seems to be caused by indeed missing **arm64e** slice in OpenSSL binaries. The package will be updated shortly to contain it.

**Comment by ilammy** [comment]
Okay, the following PRs resolve issues found:

- change in Bitrise configuration to build with Xcode 11.0.x — failures on Bitrise
- d224ffcf1b5cb04db22cb3fe3008aeb9683788b0 — CocoaPods spec linting
- cossacklabs/openssl-apple#6 — build failures seen by @vixentael due to missing architectures
- cossacklabs/openssl-apple#7 — possible failure to validate versions of Carthage installations

The `1.1.107` release of OpenSSL has also been updated. I'll throw in some commit here to trigger another build.

**Comment by ilammy** [comment]
There is another (final final final) change, adding support for arm64e to Xcode projects built by Carthage. This ensures that Carthage will built this architecture even if Xcode does not select it by default (e.g., Xcode 11 does not). Otherwise missing architecture in dependencies may prevent apps from being tested with arm64e. (As noted above, we already build OpenSSL for arm64e as well.)

**Comment by vixentael** [comment]
Here we're waiting for me to test these changes on arm64e real device (iPhone XS) tomorrow, then we'll either merge this PR or decide what to do next.

**Comment by ilammy** [comment]
We have encountered some more compilation issues related to bitcode support in Carthage for arm64e. Trying to enable it as a last ditch effort to make it work. If it doesn't, we'll probably revert recent changes.

**Comment by vixentael** [comment]
Current state of things: 
- we've tested on arm64e real device — all works as expected
- if users (either on Xcode 11 or Xcode12 beta4) add `arm64e` explicitly to their project architects, build fails due to missing bitcode in arm64e slice. We believe that currently there's nothing we can do about this, maybe arm64e will be "part of the family" with Xcode12 stable (or later).

**Comment by ilammy** [comment]
In any case, I think it's too early for us to claim full arm64e support in all use cases so I have removed those lines from the changelog (and resolved merge conflicts with master). This should the _really final_ state of this PR 🤞

**Pull request merged**
