### PR TITLE
Fix clippy and fmt issues

### PR DESCRIPTION
**Pull request by iamnotacake**
New clippy, new issues that make working code fail CI checks. Again.

Fixed clippy issues with `cargo clippy --fix --all-targets`, the formatted with `cargo fmt`.

Only cosmetic changes, most of them are outside of wrapper, i.e. in tests and benchmarks.

Update MSRV to 1.60 since our dependency `zeroize` now requires it.

Freeze two more dev deps `regex` and `memchr`, dependencies of `env_logger` used in Rust Themis tests.

## Checklist

- [x] Change is covered by automated tests
- [x] ~Benchmark results are attached (if applicable)~
- [x] The [coding guidelines] are followed
- [x] ~Public API has proper documentation~
- [x] ~Example projects and code samples are up-to-date (in case of API changes)~
- [x] ~Changelog is updated (in case of notable or breaking changes)~

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by Lagovas — APPROVED** [review]

**Comment by vixentael** [comment]
Uh..
```
error: package `zeroize v1.7.0` cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.58.1```

**Comment by iamnotacake** [comment]
> error: package `zeroize v1.7.0` cannot be built because it requires rustc 1.60 or newer

Well, there are two-and-a-half possible solutions:
1) Simply freeze `zeroize` version like I did with some other test deps that require newer compiler; basically, it's all about tests, and Themis itself does not require newer compiler
2) Update MSRV to 1.60 (released on April 2022 btw) and solve _this_ issue
2.5) Update MSRV even more (something like 1.63?) to also remove other frozen deps, solve all issues until some deps will update again and will require even newer toolchain, but that's in future

**Comment by vixentael** [comment]
i vote for (1), @Lagovas WDYT?

**Comment by Lagovas** [comment]
I vote for both cases. Freeze and update, because I see, that a lot of dependencies upgraded their dependencies (it's 3th or 4th issue like that0

**Review by G1gg1L3s — APPROVED** [review]
Clippy happy, me happy. Looks good!

**Review by Lagovas — APPROVED** [review]

**Review by vixentael — APPROVED** [review]

**Pull request merged**
