### PR TITLE
Bump embedded BoringSSL

### PR DESCRIPTION
**Pull request by G1gg1L3s**
Unfortunately, this was not so smooth as expected, but fixes are pretty easy so not a problem. Though it took me some time to figure it out. Main changes:

- Some annoying bug with relative/absolute paths in make scripts was fixed
- Some types became opaque (RSA, pkey), so they needed accessors

Locally core tests pass, so let's see what our CI will say.

## Checklist

- [x] Change is covered by automated tests
- [x] ~Benchmark results are attached (if applicable)~
- [x] The [coding guidelines] are followed
- [x] ~Public API has proper documentation~
- [x] ~Example projects and code samples are up-to-date (in case of API changes)~
- [x] Changelog is updated (in case of notable or breaking changes)

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by Lagovas** [comment]
looks like we need to update min rust version for rustthemis

**Comment by vixentael** [comment]
interesting

**Review by Lagovas — APPROVED** [review]
lgtm after pulling #1005 and green tests

**Comment by G1gg1L3s** [comment]
As during the previous release (https://github.com/cossacklabs/themis/pull/812), we can postpone the merge of this PR closer to the release itself just to get as many boringssl update as we can.

**Pull request merged**
