### PR TITLE
Improve OpenSSL 3.0 compatibility

### PR DESCRIPTION
**Pull request by ilammy**
Pull in the updates, YOLO.

If that does not work, [`man git-revert` on “How to revert a faulty merge”](https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt).

Make sure to merge this with a **merge commit**, _not squash_. Also, apparently we'd need to disable the linear history thing in branch protection to actually allow merge commits.

## Checklist

- [X] Change is covered by automated tests
- [X] ~~Benchmark results are attached~~ (people say OpenSSL 3.0 is slower, but here we don't care)
- [X] The [coding guidelines] are followed
- [X] ~~Example projects and code samples are up-to-date~~ (still using whatever they were using)
- [X] ~~Changelog is updated~~ (ninja change)

[coding guidelines]: https://github.com/cossacklabs/themis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by vixentael — APPROVED** [review]
let's do it! `do-it.jpg`

**Comment by vixentael** [comment]
github says that "This branch is out-of-date with the base branch" – i wonder if we add master into this branch, wouldn't it ruin the possible revert procedures later 🤔

**Comment by vixentael** [comment]
> Also, apparently we'd need to disable the linear history thing in branch protection to actually allow merge commits.
Screenshot 2021-12-03 at 12 40 48

👌

**Comment by ilammy** [comment]
> github says that "This branch is out-of-date with the base branch" – i wonder if we add master into this branch, wouldn't it ruin the possible revert procedures later

I've temporarily disabled that setting too, just for now. And there's _one more_ setting controlling the choice of merge options in GitHub UI.

For future reference, in order to do a merge commit via GitHub UI:

1. Settings | Branches | Branch protection rules
    1. **UNCHECK** – Require linear history
    2. **UNCHECK** – Require branches to be up to date before merging
2. Settings | Options > Merge button
    1. **CHECK** – Allow merge commits
3. Refresh the page with PR.
4. Select **Create a merge commit option**, press the big green button.
5. Revert changes to repo settings from items 1 and 2 back to their normal state.

I guess this is fine, true merge commits into master are infrequent occasions.

**Pull request merged**
