### PR TITLE
Minor fixes in SwiftThemisServerExample

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by vixentael** [comment]
Thank you for the PR!

Can you specify please the Swift version you used for these changes? I'm not able to compile your changes using Xcode 8.0 and Swift 2.3

However, we're planning to migrate to Swift 3.0 soon :)

**Comment by valeriyvan** [comment]
>Can you specify please the Swift version you used for these changes?
Trailing block syntax is in Swift at least since day it was presented publicly.

> I'm not able to compile your changes using Xcode 8.0 and Swift 2.3
No, xcode 8 will not compile this code as it is. Not because of PR. 
Try xcode 7.3.1.

>However, we're planning to migrate to Swift 3.0 soon :)
Now you see it's time to do it.

**Comment by vixentael** [comment]
Thank you, I'll take a look!

**Comment by vixentael** [comment]
Thank you, these changes now are part of #148

**Pull request closed without merging**
